# Paths to the folders to be used for encoding
# realpath will be used automatically, but using absolute paths is recommended
#
# IMPORTANT: IZUMI WILL NOT VALIDATE THIS YAML FILE

# Type of Izumi running (downloader or encoder)
type: "downloader"
#type: "encoder"

folders:
    # The directory in which new files will watched for
    # Can use absolute or local path
    watch: ""

    # Where a copy of the mkv video will be made
    mkv: ""

    # Where the hardsub mp4 will be made
    mp4: ""

    # A temporary directory used to store a copy of the mkv.
    # This temp directory may NOT contain the single quote.
    temp: ""

    # A temporary "hard" directory used by the encoders to temporarily store the new file
    # before hardlinking it to the watch directory. We do this because the system assumes
    # the file is already done downloading
    hard: ""

sync:
    # rclone folder to upload all show/ep.mkv to
    # Note: We are going to assume that rclone is already installed on the host sytsem,
    # as destinations are typically personal and should not be with the application
    # ffmpeg and ffmpeg-10bit are included as they are standalone
    mkv:
        priority: [] #rclone
        regular: [] #rclone
        encoders: 
                x264: [] #url
                x265: [] #url
                status_code: 209
                fallback: yes
    mp4:
        # If this is encoder, be careful to only add the destinations you want
        priority: [] #rclone
        regular: [] #rclone

    mp4-distribution:
        # Distributors are URLs that will be posted
        distributors:
            # For sequential distributors, they will be tried until one succeeds
            sequential: [] #url
            # For always distributors, these will always be notified regardless
            always: [] #url

        # While the others are for specifying where to send distribution requests
        # This species for the distributor where to source and where to target
        distribution:
                # Element 0: Source, element n >= 1: All destinations to target
                - [] #rclone
                - [] #rclone

        # Settings for if am an encoder
        encoder:
            port: 1400
            source: '' #rclone

notifications:
   upload:
        mkv:
            name: "MKV"
            urls: [] #url
        mp4:
            name: "MP4"
            urls: [] #url

ffmpeg:
    threads: 6 # ffmpeg threads to use

sys:
    delimiter: "||"
