# You can optionally load a global config from a web source.
# This is the folder the application will watch for new files. 
# [type: String-URL]
# This MUST be included in this config, and not the web-config.
watch-folder: "/home/rocia/Desktop"

# If you do not, leave this as an empty string.
# [type: String-URL]
web-config: ""

# Grouping body to specify the names used when uploading files
uploading:

  # A list of rclone strings for Acqusition to upload the file to
  # There must be at least one destination listed, because Acquisition
  # doesn't touch original files. Usually this is just a list of 1 element.
  # [type: A list of strings]
  upload-destinations:
    - "rclone_config:folder/"

  # This is an optional parameter which allows you to specify the name of an 
  # "Airing" folder for shows. It's recommend you use the Airing folder because
  # if switching to a web config, the Airing folder will be tacked on.
  # To not use it, simply leave it as an empty string.
  airing-folder-name: ""

# Grouping body to list endpoints for other Izumi modules for this app to talk to.
endpoints:

  # A list of U2 Encoder endpoints to send to.
  # Usually only one is here, but multiple encoder endpoints are supported (for various settings)
  # The format is a list of lists. Either list format is usable.
  # For each member in the list:
  # - Index 0 is the URL of the Encoding Unit (U2). It should include http/https. [type: String-URL]
  # - Index 1 is a an optional Authorization header token if the endpoint requires a header. [type: String-Key]
  # To have no encoders, simply have an empty list "[]"
  encoders:

    # These urls will always be notified, regardless if one fails
    always:
      - ["https://endpoint1.url/notify", "authorization_key"]
      - ["https://endpoint2.url/notify"]

    # Per each group in the list, each member in the group will be pinged
    # until one is successful.
    sequential:
      - - ["https://endpoint1.url/notify", "authorization_key"]
        - ['https://endpoint2.url/notify']
      - - ["https://endpoint3.url/notify", "authorization_key"]
        - ['https://endpoint4.url/notify']

  # A list of U3 Notification endpoints to send to.
  # The format is a list of lists. Either list format is usable.
  # For each member in the list:
  # - Index 0 is the URL of the Notification Unit (U3). It should include http/https. [type: String-URL]
  # - Index 1 is a an optional Authorization header token if the endpoint requires a header. [type: String-Key]
  # To have no notifiers, simply have an empty list "[]"
  notifiers:

    # These urls will always be notified, regardless if one fails
    always:
      - ["https://endpoint1.url/notify", "authorization_key"]
      - ["https://endpoint2.url/notify"]

    # Per each group in the list, each member in the group will be pinged
    # until one is successful.
    sequential:
      - - ["https://endpoint1.url/notify", "authorization_key"]
        - ['https://endpoint2.url/notify']
      - - ["https://endpoint3.url/notify", "authorization_key"]
        - ['https://endpoint4.url/notify']

  # A list of U4 Distributor endpoints to send to.
  # The format is a list of lists. Either list format is usable.
  # For each member in the list:
  # - Index 0 is the URL of the Distributor Unit (U4). It should include http/https. [type: String-URL]
  # - Index 1 is a an optional Authorization header token if the endpoint requires a header. [type: String-Key]
  # To have no distributors, simply have an empty list "[]"
  distributors:

    # These urls will always be notified, regardless if one fails
    always:
      - ["https://endpoint1.url/notify", "authorization_key"]
      - ["https://endpoint2.url/notify"]

    # Per each group in the list, each member in the group will be pinged
    # until one is successful.
    sequential:
      - - ["https://endpoint1.url/notify", "authorization_key"]
        - ['https://endpoint2.url/notify']
      - - ["https://endpoint3.url/notify", "authorization_key"]
        - ['https://endpoint4.url/notify']


# Application-specific settings
system:

  # This is the delimiter used by inotify to split the arguments.
  # Don't edit this unless you know what you're doing.
  # [type: String]
  delimiter: "||"

  # Whether or not the application should print more information.
  # [type: Boolean]
  verbose: Yes