# This is the port the application will listen on.
# [type: Integer]
listen-port: 80

# Authorization files must be stored locally

# You can optionally load a global config from a web source
# If you do not, leave this as an empty string
# [type: string]
web-config: ""

# Grouping body for notification specifics
notification:

  # How many notification jobs should be run at one given time 
  # For notifications, this probably doesn't need to be higher than 1 or 2
  # [type: Integer]
  jobs: 1

# Grouping body for ALL module output notifications
modules:

  # Grouping body for Discord webhooks
  # Key 'template' is an optional parameter, defaults to 1
  # If none are used, leave as an empty list []
  discord-webhook:
    - name: "zenbu"
      url: "https://discord.webhook.url/identifier"
      template: 1

# Modules, but for developer use
dev:

  # See: discord-webhook above, but this is not a list
  discord-webhook:
    name: "dev"
    url: "https://dev.discord.webhook.url/identifier"
    template: 1

# Application-specifc settings
system:

  # For testing, you can enable a "dev" setting that sends requests to 
  # an alternative "dev" grouping of settings instead
  use-dev: no

  # The identifier for this system
  # [type: String]
  name: "izumi"

  # Whether or not hte application should print more information
  # [type: Boolean]
  verbose: yes

  # Logging settings
  logging:

    # The style of the log output messages, using %(var)s style
    logfmt: "[%(name)s] (%(levelname)s) %(asctime)s: %(message)s"
    # The strftime-style format for %(asctime)s
    datefmt: "%a|%b%y %X %Z"
